title:  Taleb  Nasser
description: Etudiant de l'ECE Paris - 2e année Bachelor 
site_title: '@ressan - Taleb Nasser'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: ressan
blog_url: https://ressan.github.io/Own-Website/
email: nassertaleb@hotmail.Fr
keybase_username: XXX
twitter_username: XXX
reddit_username: XXX

# absolute or relative
profile_picture: assets/images/pp.jpg

# Google Analytics ID
google_analytics: 